# -*- coding: utf-8 -*-
"""Python in generative AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kS0WA3j1lgrXdPPuD83LlZyrjdzkr-Qx
"""

x=10
x



y=20

y

_mycity = "Solan"
_mycity

my_city1 = "New Delhi"
my_city1

1mycity = "New Delhi"
1mycity

my@college = "Shoolini University"
my@college

import keyword
keyword.kwlist

x= 1
type(x)

y= 0.0
type(y)

z= 3+4j
type(z)

#string---data in the form of text
a = "Solan"
type(a)

#boolen--it is used store a values taht is True and False
x = True
type(x)

y = False
type(y)

#None--it is null value means nothing
e =  None
type(e)

#addition
2+2

x = 4
y = 6
z = x+y
print(z)

#substraction
a = 10
b = 5
c = a-b
print(c)

#multiplication
a = 5
b = 2
c = a*b
print(c)

#division
a = 10
b = 5
c = a/b
print(c)

#expontiation
a = 2
b = 3
c = a**b
print(c)

#floor division-- return the result in whole number
7//2

7.0//2

#modulus-- the output is remainder
5%2

#single quotes string
my_sub = "Machine learning"
print(my_sub)

#doublr quotes system
my_college = "Shoolini University"
type(my_college)

#tiple quotes system
my_sentences = '''This sentence is multipline line, this is also known as string'''
type(my_sentences)

#find the length of the string
my_sub = "Machine Learning"
len(my_sub)

my_sub[0]

my_sub[1]

my_sub[15]

my_sub = "Machine learning"
my_sub[-1]

my_sub[-9]

my_sub[0:7:1]#by deafult stepsize is one

#lower()--this method used to convert string into lower case
my_sub = "PYTHON"
my_sub.lower()

#upper()--this method is used to convert string into uppercase
my_sub = "python"
my_sub.upper()

#count()--this method count particular character in string
my_string = "Machine learning"
my_string.count('a')

my_list = [78, 89, 67, 98]
type(my_list)

mixed_list = [23, 3.14, "apple", True, None]
type(mixed_list)

print(my_list)

#find the length of the list
len(my_list)

my_list = [78, 98,23, 35, 10]
print(my_list[0])
print(my_list[1])
print(my_list[2])
print(my_list[3])
print(my_list[4])

#negative indexing
my_list = [78, 89, 23,34,10]
print(my_list[-1])
print(my_list[-2])
print(my_list[-3])
print(my_list[-4])
print(my_list[-5])

my_list = [2, 3, 7, 4, 5]
my_list[0:5:1]

#bydeafult stepsize is one
my_list[0:5]

my_list[0:]

my_list[:5]

my_list[ : : -1]

#function in list
#min()--return the minimum number of the list
my_list = [98, 34, 56, 45, 12]
min(my_list)

#max()--return the maximum number of the list
max(my_list)

#sum()--return addition of aall item of the list
sum(my_list)

#sorted()--this function arrange list increasing or decreasing order
list1 = [9, 7, 12, 4, 8, 3]
sorted(list1, reverse = True)

list1

my_list = [90, 87, 65, 34]
my_list.append(100)
print(my_list)

my_list[2] = 200
print(my_list)

list1 = [90, 78, 65]
list2 = [56, 89, 45]
list1.extend(list2)
print(list1)

my_list = [78, 56, 34, 12]
my_list.pop(0)

list1 = [90, 87, 65, 22]
list1.remove(87)
list1

my_list =[90, 87, 65,23]
my_list.reverse()
print(my_list)

my_dict = {"Name" "Amut" "COllege" "SU"}
type(my_dict)
print(my_dict)

#conditional satement
age = int(input("Enter your age:"))
if age>60:
 print("You are too old for marry")
elif age<18:
 print("You are too young to marry")
else:
  print("We will find perfect match for you")

my_dict.key()
dict.key["Name", "College"]
list(my_list.key)



my_sub = "Python"
for i in my_sub:
  print(i)

for i in range(0, 6, 1):
  print(i)

for i in range(0,6):
  print(i)

for i in range(6):
  print(i)

my_sub = "Python"
for i in range(len(my_sub)):
  print(my_sub[i], "=", i)

#while loop
i = 0 #inilization
while i<5: #condition
 print(i)
 i+=1 #increment

#loop and control statement
#break -- this statement break the loopn
i = 0
while i<5:
  i+=1 #incement
  if i==3:
    break
  else:
       print(i)

#continue statement -- this statement skip the current ileration
i = 0
while i<5:
  i+=1
  if i==3:
    continue
    print(i)
  else:
    print(i)

#pass satement  -- this satement pass the code
i = 0
while i<5:
  i+=1
  if i==3:
    pass
    print(i)
  else:
    print(i)

#user defined function without argument
def add():
  a = int(input("Eneter the first number: "))
  b = int(input("Enter the secind number: "))
  return a+b
  add()

add()

#positional argument
def calculation(a, b):
  print("addition", a+b)
  print("substraction", a-b)
  print("multiplication", a*b)
  print("division", a/b)
  return "Calcultion is complete"

print(calculation(10, 5))

#defaukt argument
def area_perimeter(width=4, height=8):
  area = width*height
  perimeter = 2*(width + height)
  return "Area is", area, "and perimeter is", perimeter

print(area_perimeter(10,20))

#keyword argument
def interest(p,r, t):
  i = (p*r*t)/100
  return i

print(interest(r = 10, t = 2, p = 1000))

#mixed argument
#positional argument follows keyword argument
print(interest(1000, t = 2, r = 10))

print(innterest(r = 10, p = 1000, 2))

#variable length  argument
#non keyword postional variable length argument
def test(*args):
  print(args)
  print(len(args))
  print(type(args))

test(2, 3, 4, 8, 9, 7)

def sum_number(*args):
  sum = 0
  for num in args:
    sum+=num
    return sum

sum_number(3, 5, 6, 7, 8, 9)

def multiplication_number(*args):
  multiplication = 1
  for multiplication in args:
    multiplication*=number
    return multiplication

multiplication_number(3, 4)

#keyword variable length argument
def test(**kwargs):
  print(kwargs)
  print(type(kwargs))
  print(len(kwargs))

test(a = 10, b = 20, c = 30)

def pass_students(**kwargs):
  pass_students_list = []
  for name, marks in kwargs.items():
    if marks>35:
      pass_students_list.append(name)
  return pass_students_list

pass_students(A = 30, B = 40, C = 50, D = 80, E = 20)

import numpy as np

#one dimensional array
oned_array = np.array([1, 2, 3])
print(oned_array)

#two dimensional array
twod_array = np.array([[1, 2, 3], [4, 5, 6]])
print(twod_array)

#row vector
row_vector = np.array([[1, 3,2]])
print(row_vector)

column_vector = np.array([[1], [2], [3]])
print(column_vector)

column_vector = row_vector.transpose()
print(column_vector)

#ndim -- find the dimention of vector
column_vector.ndim

#size -- find the number of items
column_vector.size

#shape
column_vector.shape

print(column_vector)

row_vector.shape

print(twod_array[0])

print(twod_array[-2])

print(twod_array[1][2])

print(twod_array[0][1])

print(twod_array[0,1])

print(twod_array[0:2,0:1])

threed_array = np.random.randint(1, 10, (3, 3))
print(threed_array)

print(threed_array[0:2, 0:2 ])

#import numpy as np
mat1 = np.matrix("1, 2, 3; 4, 5, 6; 7, 8, 9")
print(mat1)

mat2 = np.matrix([[1, 2, 3],[4, 5, 6]])
print(mat2)

mat3 = np.random.random((3, 3))
print(mat3)

mat4 = np.random.randint(1, 20, (3, 3))
print(mat4)

np.zeros_array = np.zeros((3, 3))
print(np.zeros_array)

zeros_array = np.zeros((3, 3), dtype = int)
print(zeros_array)

ones_array = np.ones((3, 3), dtype = int)
print(ones_array)

ones_array = np.ones((3, 3), dtype = int)
print(ones_array*100)

my_array = np.array([1, 2, 3, 4])
print(my_array)

power_array = np.power(my_array, 2)
print(power_array)

exp_array = np.exp(my_array)
print(exp_array)

exp_array = np.exp(my_array)
print(my_array)

log_array = np.log(my_array)
print(log_array)

log2_array = np.log2(my_array)
print(log2_array)

log10_array = np.log10(my_array)
print(log10_array)

a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))
print(a)
print(b)

print(np.dot(a, b))

import pandas as pd

#Series-- one dimensional data structure of pandas
my_series = pd.Series(["Apple", "Banana", "Mango", "Orange"], name = "Fruits")
my_series

#DataFrame--two dimensional data structure of pandas
import pandas as pd
list_into_list = [["Amar",15], ["Akbar",14], ["Anthony",13]]
df = pd.DataFrame(list_into_list, columns = ["Name", "Age"])
df

df_movies = pd.read_csv("/content/drive/MyDrive/My Data/imdb_data.csv")
df_movies

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
#head()--bring row(data point) from top of the dataframe
df = pd.read_csv("/content/drive/MyDrive/My Data/imdb_data.csv")
df.head()

#tail()--bring the row(data point) form bottom of the data frame
df.tail()

#find the number of row and column in the data frame
df.shape

#find the name of the all columns
df.columns

#bring the rows(data point) randomly from the data
df.sample(5)

#find the information of the data
df.info()

#how does the data look like mathematically
df.describe()

#find the duplicate value
print(df.duplicated().sum())

#find the null value
df.isnull().sum()

df.columns

#slicing and indexing
#find the single column with all row
df["title"]

#multiple column with all rows
df[["title", "budget", "revenue", "original_language"]]

#slicing with help of rows
df[0:4]

#find the some number of rows and columns
df.iloc[0:4, 0:3]

df.loc[0:4, ["title", "budget", "revenue"]]

#find the unique value in particular column
df_movies["original_language"].unique()

df["original_language"] == "en"

english_movies = df[df["original_language"] == "en"]
english_movies

#how to  write a file in csv formate
english_movies.to_csv("english_movies.csv")







